---
- name: Create directory /etc/opt/live with root:root ownership
  hosts: "{{ target_hosts }}"
  tasks:
    - name: Ensure the destination directory exists on the local host
      local_action: 
        module: file
        path: "/tmp/src/"
        state: directory
        owner: root
        group: root
        mode: '0755'
      run_once: True

    - name: Copy /tmp/src directory from target to local
      synchronize:
        src: /tmp/src/
        dest: /tmp/src/
        mode: pull # Ensure we are pulling the files from the remote host to the control machine
      delegate_to: localhost

    - name: Create directory /etc/opt/live
      file:
        path: /etc/opt/live
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Synchronize files and directories
      ansible.posix.synchronize:
        src: /tmp/src
        dest: /etc/opt/live
        recursive: yes
        perms: True
      